# Generated by Django 2.2.3 on 2019-07-29 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='p',
        ),
        migrations.AddField(
            model_name='index',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='index',
            name='share_text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
