# Generated by Django 2.2.3 on 2019-07-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20190729_0904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='DareText',
        ),
    ]
