# Generated by Django 2.2.3 on 2019-07-30 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20190729_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke_text', models.CharField(default='', max_length=5000)),
                ('joke_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='QuotesText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes_text', models.CharField(default='', max_length=5000)),
                ('quotes_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
